add E-R
bitswitches/IflavorServer pull request #24
Opened 2017-12-05 13:04 UTC by shotaws

add E-R picture

2017-12-07 06:05 UTC, kokeshi92 requested changes
各テーブルに対して、primary key？なのかな、
tablename_id(order_id, history_idなど) という形で設けてると思いますが、冗長かなと感じました。普通にidでいいかと。

2017-12-07 06:09 UTC, jinshikoike commented
orderが購入リクエスト？を管理するテーブルですかね？
historyなくて、orderだけでいいのではと感じましたがどうでしょうか？

2017-12-07 06:13 UTC, jinshikoike commented
belongingsテーブルについて
これは今までそのユーザーitemを何個買ってきたかっていうテーブルですかね？
だとしたらorderテーブルだけで足りるかと思いました。

ユーザーが今何個もっているかについては、管理できないと思ってます。今の要件だと配送されてしまえば、どう使うかはユーザーに依存するので。

2017-12-10 00:51 UTC, shotaws commented
更新しました。
・テーブルの整理
・トレーサビリティを意識した時間フィールド（created_at、updated_at）追加
・元ファイルの追加（MySQL Workbenchのファイル）
https://github.com/bitswitches/IflavorServer/pull/24/commits/f786f880ba20e80c5c30c909038ed175c7036c77

2017-12-10 14:52 UTC, jinshikoike commented
ER2見ればいいですよね？

2017-12-10 14:52 UTC, jinshikoike commented
こんな感じでいいと思いますb

マージしちゃいますね！

2017-12-10 14:52 UTC, kokeshi92 approved these changes
LGTM:+1:

2017-12-10 14:52 UTC, merged

2017-12-10 14:53 UTC, jinshikoike commented
またなにかあったら、ここから微調整って感じでいきましょう〜