API設計しました
bitswitches/IflavorServer pull request #25
Opened 2017-12-06 13:44 UTC by keikosanjo

* 対象のissue
https://github.com/bitswitches/IflavorServer/issues/9

* 勝手にdocsの中に入れちゃったので、変更などあれば指摘お願いします。

2017-12-07 06:16 UTC, jinshikoike commented
pr #24　でコメントしたので、それ次第で変わってきそうですね。それまでレビュー待ちます。

2017-12-18 12:12 UTC, keikosanjo commented
遅くなってごめんなさい！一度修正されたテーブルを元にAPI設計し直してみました。
テーブル作成のとこでコメントされてたけど、今保持している香水情報はもてないのかな？
アプリ内で残量とか表示するのにいるのかなあと思ったのだけど・・・
とりあえずレビューをお願いします！

2017-12-21 23:42 UTC, kokeshi92 requested changes
please fix

2017-12-21 23:42 UTC, jinshikoike commented on docs/api/fix_API.eyaml
> +  /user:
この場合はuser(単数系) を users(複数形）にしたほうが、一般的っぽいです。

2017-12-21 23:42 UTC, jinshikoike commented on docs/api/fix_API.eyaml
> +  /user:
↓の単数形になっているものも同じです。

2017-12-21 23:42 UTC, jinshikoike commented on docs/api/fix_API.eyaml
> +      - in:  "path"
postやputの時は- inでpathを設定することは基本ないと思うので消しちゃってください。

2017-12-21 23:42 UTC, jinshikoike commented on docs/api/fix_API.eyaml
> +      - in:  "path"
他に同じような部分あれば、消しましょう

2017-12-21 23:42 UTC, jinshikoike commented on docs/api/fix_API.eyaml
> +  /situation:
シチュエーションはDBになかった気がします。
とりあえずは、デバイス側で固定化してしまい、余裕あったら今後拡張していきましょう。

2017-12-26 12:16 UTC, keikosanjo commented on docs/api/fix_API.eyaml
> +  /user:
"fixed_API.eyml"をチェックお願いします。
ごちゃごちゃして消してしまいました、ごめんなさい！
複数形に変更しました。

2017-12-26 12:16 UTC, keikosanjo commented on docs/api/fix_API.eyaml
> +      - in:  "path"
恐らく確認出来たところ全部、消しました。

2017-12-26 12:16 UTC, keikosanjo commented on docs/api/fix_API.eyaml
> +  /situation:
了解です！シチュエーションに関して消しました！

2017-12-26 12:17 UTC, keikosanjo commented
"fixed_API.eyml"の確認お願いします！

2018-01-11 16:14 UTC, kokeshi92 approved these changes
とりあえずokだと思うのでマージします。

2018-01-11 16:14 UTC, merged